spring.application.name=s3-spring-demo

# AWS Configuration (TODO: Fill these with your actual details)
aws.access-key=TODO_FILL_YOUR_ACCESS_KEY
aws.secret-key=TODO_FILL_YOUR_SECRET_KEY
aws.region=TODO_FILL_YOUR_AWS_REGION
aws.s3.bucket-name=TODO_FILL_YOUR_BUCKET_NAME
